[package]
name = "mdns-alias"
version = "0.1.0"
edition = "2024"
rust-version = "1.98"
license = "0BSD"
description = "Publish extra mDNS host names for this machine"
publish = false

[dependencies]
ctrlc = { version = "3.5.2", features = ["termination"] }
mdns-sd = { version = "0.21.4", default-features = false }

[profile.release]
codegen-units = 1
lto = true
panic = "abort"
strip = true
